---
title: "DSggplot_28144146"
author: "Nishi Parikh (28144146)"
date: "version `r format (Sys.time(), '%B %d, %Y')`"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
---
#running tidyverse 
```{r}
install.packages("stringr")
install.packages("tidyverse")
library(tidyverse)
```

#phyloseq packages
```{r}
source("https://bioconductor.org/biocLite.R")
biocLite("phyloseq")
library(phyloseq)
```
#load data  
```{r}
load("phyloseq_object.RData")
```
#exercise 1
```{r echo=TRUE, message=FALSE, warning=FALSE}
#geom_point must be specified for shape, colour and size 
ggplot(metadata,aes(x=PO4_uM, y=Depth_m)) +
  geom_point(shape=17, colour="purple")
```
#exercise 2 
```{r echo=TRUE, message=FALSE, warning=FALSE}
#convert temperature from C to F and plot against depth. 
metadata %>% 
  mutate(Temperature_F = 1.8*Temperature_C + 32) %>%
ggplot(aes(Temperature_F, y=Depth_m)) +
  geom_point()

```
#exercise 3
```{r echo=TRUE, fig.width=20, fig.height=10, message=FALSE, warning=FALSE}
#convert to percentages
#Using "Order" create a ggplot
#add title, x label and y laberl

physeq_percent = transform_sample_counts(physeq, function(x) 100 * x/sum(x))
plot_bar(physeq_percent, fill="Order") + 
  geom_bar(aes(fill=Order), stat="identity") +
   ggtitle("Orders from 10-200m in Saanich Inlet") +
  xlab("Sample depth") + ylab("Percent relative abundance")


```
#exercise 4
```{r echo=TRUE, message=FALSE, warning=FALSE}

#gather nutrient data for all 
#create a gg plot for nutrient vs depth 
metadata %>% 
  gather(Nutrients_uM, uM, NH4_uM, NO2_uM, NO3_uM, O2_uM, PO4_uM, SiO2_uM) %>%
  ggplot() +geom_point(aes(x=Depth_m, y=uM)) + geom_line(aes(x=Depth_m, y=uM)) +
 facet_wrap(~Nutrients_uM, scales="free_y") 


```
